### PR TITLE
RA-968 Built module for OpenMRS 2.0 platform

### PR DESCRIPTION
**Pull request by jdegraft**

### CODE REVIEW

**Comment by dkayiwa** [comment]
This seems to be doing more than it is supposed to.

**Comment by jdegraft** [comment]
The existing code creates a new user though and is trying to save the user with a password.

**Comment by djazayeri** [comment]
About users, I would presume you can change the test code to save the user in a more straightforward way that doesn't require different logic for different versions (e.g. just give the user a password).

More broadly, it seems like lots of stuff is changing because you are trying to preserver a portlet, and homepage override behavior in the 1.x UI. I don't think it is necessary to preserve this.

In the years since that code was written, the way things have evolved is that App Framework is a fundamental piece of the reference application (and Bahmni, and other distros), but it isn't really used with the 1.x line of the UI.

So, my counterproposal is to just remove anything that has to do with the 1.x UI, which should simplify this PR significantly.

**Comment by jdegraft** [comment]
@djazayeri, I am not sure I understand this proposal.

The only change to code is to support the difference in saveUser interface which is only used in 1 test which is why I opted for reflection rather than separate modules. It seems drastic to remove support for 1.x line because of that. Unless we want to remove support for 1.x line for other reasons.

There were some other changes which @dkayiwa  rejected which I am still looking into an alternate solution. That problem is to do with DirtiesContext annotation, once again only used in tests. However in this case the problem is actually with platform 2.0. So in this case removing support for 1.x line will not solve the problem.

**Pull request closed without merging**
