### PR TITLE
AF-58: Support openmrs platform 2.3.x

### PR DESCRIPTION
**Pull request by ODORA0**
**Issue worked on:** https://issues.openmrs.org/browse/AF-58

### CODE REVIEW

**Comment by ODORA0** [comment]
This is another wired Travis failure when I have a successful local build @dkayiwa

**Comment by dkayiwa** [comment]
Do you take time to look at the error message?

**Comment by ODORA0** [comment]
That's what am doing though

**Comment by ODORA0** [comment]
I have been figuring out what the prob here is but line 149 and 166 in the `AppFrameworkServiceImplTest.java` seems ok because in my IDE code seems unchanged `assertEquals(2, extensionPoints.size());` for 149 and ` assertEquals(2, extensionPoints.size());` for 166 since Travis says expected <2> and there is <0>

**Comment by HerbertYiga** [comment]
@dkayiwa   I happen to face the same exact issue as seen here https://github.com/openmrs/openmrs-module-appframework/pull/30

**Comment by samuelmale** [comment]
Does the error turn-up locally?

**Comment by ODORA0** [comment]
@dkayiwa I think this PR is good to go after I re-based these changes https://github.com/openmrs/openmrs-module-appframework/pull/36 which I realised from this [TALK POST](https://talk.openmrs.org/t/failing-test-by-travis-within-appframe-work/23286) cc @HerbertYiga

**Pull request merged**
