### PR TITLE
RA-923:Adding the getAllExtensions service method without extension Point Id

### PR DESCRIPTION
**Pull request by gitcliff**
link: https://issues.openmrs.org/browse/RA-923

### CODE REVIEW

**Comment by gitcliff** [comment]
Hello @dkayiwa i have added this pr as part of this  ticket https://issues.openmrs.org/browse/RA-923 in order to introduce the getAllExtensions() in the App framework module service class so that i can use it in the manageExtensions controller class of RA module 

Kindly review

**Comment by dkayiwa** [comment]
What is the use of this method?

**Comment by gitcliff** [comment]
@dkayiwa  this method i meant to fetch all Extensions and i also came across this  https://issues.openmrs.org/browse/AF-27 created by @mogoodrich  which i think this pr can best address...
requesting for your guidance

**Comment by dkayiwa** [comment]
Since AF-27 was closed with Won't Fix, am likewise closing this.
Sorry about this @gitcliff

**Pull request closed without merging**
